#! /bin/sh
### BEGIN INIT INFO
# Provides:          brokername
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the MARCOS/collector.py script
# Description:       see short
#                    
### END INIT INFO

# /etc/init.d/marcos

# Some BASIC definitions
# #####################################
PS="/bin/ps"
GREP="/bin/grep"
ECHO="/bin/echo"
WC="/usr/bin/wc"
AWK="/usr/bin/awk"
KILL="/bin/kill"
SLEEP="/bin/sleep"


###  You should use several marcos start scripts for
###  accessing different brokers e.g. marcos-broker1.
###  Add the respective broker below

# # Define a python path if not using default python
PYTHONPATH='/usr/bin/python' #/home/cobs/anaconda2/bin/python'

# # Your Local Marcos directory 
MARCOSPATH='/your/collectorpath'

# # Your Local config directory 
CONFPATH='/etc/marcos/'

# # The main collector program
# # Please consider the space before options if provided"
BROKER="brokername"
COLL="collector.py"
COLLOPT="optionsline"  # like -b mybroker -d mydb -r athome -o mystation (or -m $CONFPATH)
PIDTEST="[c]ollector.py$COLLOPT"
COLLPROG="$COLL$COLLOPT"

# # change delay (necessary for systemstart and proper restart)
DELAY=20

# Some methods
# #####################################
check_process()
{
    # Check if the process is already running. Ignore $GREP line.
    result=`$PS aux | $GREP "$COLLPROG" | $GREP -v $GREP | $WC -l`
}

get_pid()
{
    pid=`$PS -ef | $AWK -v pattern="$PIDTEST" '$0 ~ pattern{print $2}'`
}

# Carry out specific functions when asked to by the system
# #####################################
case "$1" in
  start)
    check_process
    if [ "$result" = "1"  ]; then
       $ECHO "$COLLPROG is already running"
    else
       $ECHO "Starting MARCOS collector $BROKER (in $DELAY sec)"
       $ECHO "--------------------"
       $SLEEP $DELAY
       cd $MARCOSPATH
       $PYTHONPATH $COLLPROG &
    fi
    ;;
  stop)
    check_process
    get_pid
    if [ "$result" = "0"  ]; then
       $ECHO "$COLLPROG is not running"
    else
       $ECHO "Stopping MARCOS $BROKER"
       $ECHO "--------------------"
       $KILL -9 $pid
       $ECHO "... stopped"
    fi
    ;;
  status)
    check_process
    if [ "$result" = "1"  ]; then
       $ECHO "$COLLPROG is running"
    else
       $ECHO "$COLLPROG process is dead"
    fi
    ;;
  restart)
    check_process
    if [ "$result" = "0"  ]; then
       $ECHO "$COLLPROG is not running"
    else
       get_pid
       $ECHO "Stopping MARCOS $BROKER"
       $ECHO "--------------------"
       $KILL -9 $pid
       $ECHO "... stopped"
    fi
    $ECHO "Starting MARCOS (in $DELAY sec)"
    $ECHO "--------------------"
    $SLEEP $DELAY
    cd $MARCOSPATH
    $PYTHONPATH $COLLPROG &
    ;;
  *)
    $ECHO "Usage: /etc/init.d/$BROKER {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
