#! /bin/sh
### BEGIN INIT INFO
# Provides:          martas
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the MARTAS/acquisition.py script
# Description:       see short
#                    
### END INIT INFO

# /etc/init.d/martas

# Some BASIC definitions  # please edit
# #####################################
PS="/bin/ps"
GREP="/bin/grep"
ECHO="/bin/echo"
WC="/usr/bin/wc"
AWK="/usr/bin/awk"
KILL="/bin/kill"
SLEEP="/bin/sleep"

# # Define a python path if not using default python
PYTHONPATH='/usr/bin/python'

# # Your Local Martas directory 
MARTASPATH='/your/acquisitionpath'

# # The main acquisition program
# # Please consider the space before options if provided"
ACQUNAME="acquisitionname"
ACQU="acquisition.py"
#Default
ACQUOPT="optionsline"
#Authentication
#ACQUOPT=" -m /home/cobs/martas.cfg -c mqtt"
PIDTEST="[a]cquisition.py$ACQUOPT"
ACQUPROG="$ACQU$ACQUOPT"

# # change delay (necessary for systemstart and proper restart)
DELAY=30

# Some methods
# #####################################
check_process()
{
    # Check if the process is already running. Ignore grep line.
    result=`$PS aux | $GREP "$ACQUPROG" | $GREP -v $GREP | $WC -l`
}

get_pid()
{
    pid=`$PS -ef | $AWK -v pattern="$PIDTEST" '$0 ~ pattern{print $2}'`
}

# Carry out specific functions when asked to by the system
# #####################################
case "$1" in
  start)
    check_process
    if [ "$result" = "1"  ]; then
       $ECHO "$ACQUPROG is already running"
    else
       $ECHO "Starting MARTAS acquisition script $ACQUNAME (in $DELAY sec)"
       $ECHO "--------------------"
       $SLEEP $DELAY
       cd $MARTASPATH
       $PYTHONPATH $ACQUPROG &
    fi
    ;;
  stop)
    check_process
    get_pid
    if [ "$result" = "0"  ]; then
       $ECHO "$ACQUPROG is not running"
    else
       $ECHO "Stopping MARTAS acquisition script $ACQUNAME"
       $ECHO "--------------------"
       $KILL -9 $pid
       $ECHO "... stopped"
    fi
    ;;
  status)
    check_process
    if [ "$result" = "1"  ]; then
       $ECHO "$ACQUPROG is running"
    else
       $ECHO "$ACQUPROG process is dead"
    fi
    ;;
  restart)
    check_process
    if [ "$result" = "0"  ]; then
       $ECHO "$ACQUPROG is not running"
    else
       get_pid
       $ECHO "Stopping MARTAS acquisition script $ACQUNAME"
       $ECHO "--------------------"
       $KILL -9 $pid
       $ECHO "... stopped"
    fi
    $ECHO "Starting acquisition script $ACQUNAME (in $DELAY sec)"
    $ECHO "--------------------"
    $SLEEP $DELAY
    cd $MARTASPATH
    $PYTHONPATH $ACQUPROG &
    ;;
  *)
    $ECHO "Usage: /etc/init.d/$ACQUNAME {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
