#! /bin/sh
### BEGIN INIT INFO
# Provides:          telegrambot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the telegrambot.py script
# Description:       see short
#                    
### END INIT INFO

# /etc/init.d/telegrambot

# Some BASIC definitions  # please edit
# #####################################
PS="/bin/ps"
GREP="/bin/grep"
ECHO="/bin/echo"
WC="/usr/bin/wc"
AWK="/usr/bin/awk"
KILL="/bin/kill"
SLEEP="/bin/sleep"

# # Define a python path if not using default python
PYTHONPATH='/usr/bin/python'

# # Your Local Martas directory 
BOTPATH='/your/botpath'

# # The main acquisition program
# # Please consider the space before options if provided"
BOT="telegrambot.py"
PIDTEST="[t]elegrambot.py"


# # change delay (necessary for systemstart and proper restart)
DELAY=2

# Some methods
# #####################################
check_process()
{
    # Check if the process is already running. Ignore grep line.
    result=`$PS aux | $GREP "$BOT" | $GREP -v $GREP | $WC -l`
}

get_pid()
{
    pid=`$PS -ef | $AWK -v pattern="$PIDTEST" '$0 ~ pattern{print $2}'`
}

# Carry out specific functions when asked to by the system
# #####################################
case "$1" in
  start)
    check_process
    if [ "$result" = "1"  ]; then
       $ECHO "$BOT is already running"
    else
       $ECHO "Starting telegram bot (in $DELAY sec)"
       $ECHO "--------------------"
       $SLEEP $DELAY
       cd $BOTPATH
       $PYTHONPATH $BOT &
    fi
    ;;
  stop)
    check_process
    get_pid
    if [ "$result" = "0"  ]; then
       $ECHO "$BOT is not running"
    else
       $ECHO "Stopping telegram bot"
       $ECHO "---------------------"
       $KILL -9 $pid
       $ECHO "... stopped"
    fi
    ;;
  status)
    check_process
    if [ "$result" = "1"  ]; then
       $ECHO "$BOT is running"
    else
       $ECHO "$BOT process is dead"
    fi
    ;;
  restart)
    check_process
    if [ "$result" = "0"  ]; then
       $ECHO "$BOT is not running"
    else
       get_pid
       $ECHO "Stopping telegram bot with $pid"
       $ECHO "--------------------"
       $KILL -9 $pid
       $ECHO "... stopped"
    fi
    $ECHO "Starting telegram bot (in $DELAY sec)"
    $ECHO "--------------------"
    $SLEEP $DELAY
    cd $BOTPATH
    $PYTHONPATH $BOT &
    ;;
  *)
    $ECHO "Usage: /etc/init.d/telegrambot {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
